language: cpp
compiler: gcc

install:
  - sudo apt-add-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-add-repository ppa:zoogie/sdl2-snapshots -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-7 g++-7 libgl1-mesa-dev libsdl2-dev
  - export CXX="g++-7" CC="gcc-7"
  - git clone https://github.com/premake/premake-core.git ../premake-core
  - cd ../premake-core
  - git checkout tags/v5.0.0-alpha13
  - git submodule init
  - git submodule update
  - make -f Bootstrap.mak linux
  - chmod +x bin/release/premake5 
  - cd $TRAVIS_BUILD_DIR
  - ../premake-core/bin/release/premake5 shaders
  - ../premake-core/bin/release/premake5 gmake
  - cd build

script:
  make config=release_x86_64
  
before_deploy:
  tar pczf renderer_bgfx_x86_64.tar.gz --directory="bin_x64" renderer_bgfx_x86_64.so
  
deploy:
  skip_cleanup: true
  provider: bintray
  file: ../.bintray.json
  user: jpcy
  key: $BINTRAY_API_KEY
  
notifications:
  email: false
